# Generated by Django 4.0.6 on 2023-02-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_board',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_task_set', to='tasks.tasks_board'),
        ),
    ]
