# Generated by Django 4.0.6 on 2023-02-11 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks_task_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
