# Generated by Django 4.0.6 on 2023-02-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.CharField(max_length=20),
        ),
    ]
