# Generated by Django 4.0.6 on 2023-02-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_tasks_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
